services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data/:rw
  app:
    container_name: app
    image: app
    build: app
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "80:8080"
    depends_on:
      - postgres
volumes:
  postgres_data:
  redis_data:
