package serializers

type Player struct {
  AccelerationRating       uint8  `json:"acceleration_rating" binding:"required"`
  Age                      uint8  `json:"age" binding:"required"`
  AgilityRating            uint8  `json:"agility_rating" binding:"required"`
  AwarenessRating          uint8  `json:"awareness_rating" binding:"required"`
  BallCarrierVisionRating  uint8  `json:"ball_carrier_vision_rating" binding:"required"`
  BirthDate                string `json:"birth_date" binding:"required"`
  BlockSheddingRating      uint8  `json:"block_shedding_rating" binding:"required"`
  BreakSackRating          uint8  `json:"break_sack_rating" binding:"required"`
  BreakTackleRating        uint8  `json:"break_tackle_rating" binding:"required"`
  CarryingRating           uint8  `json:"carrying_rating" binding:"required"`
  CatchInTrafficRating     uint8  `json:"catch_in_traffic_rating" binding:"required"`
  CatchingRating           uint8  `json:"catching_rating" binding:"required"`
  ChangeOfDirectionRating  uint8  `json:"change_of_direction_rating" binding:"required"`
  College                  string `json:"college" binding:"required"`
  DeepRouteRunningRating   uint8  `json:"deep_route_running_rating" binding:"required"`
  FinesseMovesRating       uint8  `json:"finesse_moves_rating" binding:"required"`
  FirstName                string `json:"first_name" binding:"required"`
  Handedness               string `json:"handedness" binding:"required"`
  Height                   uint8  `json:"height" binding:"required"`
  HitPowerRating           uint8  `json:"hit_power_rating" binding:"required"`
  ImpactBlockingRating     uint8  `json:"impact_blocking_rating" binding:"required"`
  InjuryRating             uint8  `json:"injury_rating" binding:"required"`
  JerseyNum                uint8  `json:"jersey_num" binding:"required"`
  JukeMoveRating           uint8  `json:"juke_move_rating" binding:"required"`
  JumpingRating            uint8  `json:"jumping_rating" binding:"required"`
  KickAccuracyRating       uint8  `json:"kick_accuracy_rating" binding:"required"`
  KickPowerRating          uint8  `json:"kick_power_rating" binding:"required"`
  KickReturnRating         uint8  `json:"kick_return_rating" binding:"required"`
  LastName                 string `json:"last_name" binding:"required"`
  LeadBlockRating          uint8  `json:"lead_block_rating" binding:"required"`
  ManCoverageRating        uint8  `json:"man_coverage_rating" binding:"required"`
  MediumRouteRunningRating uint8  `json:"medium_route_running_rating" binding:"required"`
  OverallRating            uint8  `json:"overall_rating" binding:"required"`
  PassBlockFinesseRating   uint8  `json:"pass_block_finesse_rating" binding:"required"`
  PassBlockPowerRating     uint8  `json:"pass_block_power_rating" binding:"required"`
  PassBlockRating          uint8  `json:"pass_block_rating" binding:"required"`
  PlayActionRating         uint8  `json:"play_action_rating" binding:"required"`
  PlayRecognitionRating    uint8  `json:"play_recognition_rating" binding:"required"`
  Position                 string `json:"position" binding:"required"`
  PowerMovesRating         uint8  `json:"power_moves_rating" binding:"required"`
  PressRating              uint8  `json:"press_rating" binding:"required"`
  PursuitRating            uint8  `json:"pursuit_rating" binding:"required"`
  ReleaseRating            uint8  `json:"release_rating" binding:"required"`
  RunBlockFinesseRating    uint8  `json:"run_block_finesse_rating" binding:"required"`
  RunBlockPowerRating      uint8  `json:"run_block_power_rating" binding:"required"`
  RunBlockRating           uint8  `json:"run_block_rating" binding:"required"`
  RunningStyleRating       string `json:"running_style_rating" binding:"required"`
  ShortRouteRunningRating  uint8  `json:"short_route_running_rating" binding:"required"`
  SpectacularCatchRating   uint8  `json:"spectacular_catch_rating" binding:"required"`
  SpeedRating              uint8  `json:"speed_rating" binding:"required"`
  SpinMoveRating           uint8  `json:"spin_move_rating" binding:"required"`
  StaminaRating            uint8  `json:"stamina_rating" binding:"required"`
  StiffArmRating           uint8  `json:"stiff_arm_rating" binding:"required"`
  StrengthRating           uint8  `json:"strength_rating" binding:"required"`
  TackleRating             uint8  `json:"tackle_rating" binding:"required"`
  Team 										 string `json:"team" binding:"required"`
  ThrowAccuracyDeepRating  uint8  `json:"throw_accuracy_deep_rating" binding:"required"`
  ThrowAccuracyMidRating 	 uint8  `json:"throw_accuracy_mid_rating" binding:"required"`
  ThrowAccuracyShortRating uint8  `json:"throw_accuracy_short_rating" binding:"required"`
  ThrowOnTheRunRating 		 uint8  `json:"throw_on_the_run_rating" binding:"required"`
  ThrowPowerRating 				 uint8  `json:"throw_power_rating" binding:"required"`
  ThrowUnderPressureRating uint8  `json:"throw_under_pressure_rating" binding:"required"`
  ToughnessRating 				 uint8  `json:"toughness_rating" binding:"required"`
  TruckingRating 					 uint8  `json:"trucking_rating" binding:"required"`
  Weight 									 uint16 `json:"weight" binding:"required"`
  NumYears             	   uint8  `json:"num_years" binding:"required"`
  ZoneCoverageRating 			 uint8  `json:"zone_coverage_rating" binding:"required"`
}
