package models

type Player struct {
  ID                       uint32   `json:"id" gorm:"primary_key"`
  AccelerationRating       uint8  `json:"acceleration_rating"`
  Age                      uint8  `json:"age"`
  AgilityRating            uint8  `json:"agility_rating"`
  AwarenessRating          uint8  `json:"awareness_rating"`
  BallCarrierVisionRating  uint8  `json:"ball_carrier_vision_rating"`
  BirthDate                string `json:"birth_date"`
  BlockSheddingRating      uint8  `json:"block_shedding_rating"`
  BreakSackRating          uint8  `json:"break_sack_rating"`
  BreakTackleRating        uint8  `json:"break_tackle_rating"`
  CarryingRating           uint8  `json:"carrying_rating"`
  CatchInTrafficRating     uint8  `json:"catch_in_traffic_rating"`
  CatchingRating           uint8  `json:"catching_rating"`
  ChangeOfDirectionRating  uint8  `json:"change_of_direction_rating"`
  College                  string `json:"college"`
  DeepRouteRunningRating   uint8  `json:"deep_route_running_rating"`
  FinesseMovesRating       uint8  `json:"finesse_moves_rating"`
  FirstName                string `json:"first_name"`
  Handedness               string `json:"handedness"`
  Height                   uint8  `json:"height"`
  HitPowerRating           uint8  `json:"hit_power_rating"`
  ImpactBlockingRating     uint8  `json:"impact_blocking_rating"`
  InjuryRating             uint8  `json:"injury_rating"`
  JerseyNum                uint8  `json:"jersey_num"`
  JukeMoveRating           uint8  `json:"juke_move_rating"`
  JumpingRating            uint8  `json:"jumping_rating"`
  KickAccuracyRating       uint8  `json:"kick_accuracy_rating"`
  KickPowerRating          uint8  `json:"kick_power_rating"`
  KickReturnRating         uint8  `json:"kick_return_rating"`
  LastName                 string `json:"last_name"`
  LeadBlockRating          uint8  `json:"lead_block_rating"`
  ManCoverageRating        uint8  `json:"man_coverage_rating"`
  MediumRouteRunningRating uint8  `json:"medium_route_running_rating"`
  OverallRating            uint8  `json:"overall_rating"`
  PassBlockFinesseRating   uint8  `json:"pass_block_finesse_rating"`
  PassBlockPowerRating     uint8  `json:"pass_block_power_rating"`
  PassBlockRating          uint8  `json:"pass_block_rating"`
  PlayActionRating         uint8  `json:"play_action_rating"`
  PlayRecognitionRating    uint8  `json:"play_recognition_rating"`
  Position                 string `json:"position"`
  PowerMovesRating         uint8  `json:"power_moves_rating"`
  PressRating              uint8  `json:"press_rating"`
  PursuitRating            uint8  `json:"pursuit_rating"`
  ReleaseRating            uint8  `json:"release_rating"`
  RunBlockFinesseRating    uint8  `json:"run_block_finesse_rating"`
  RunBlockPowerRating      uint8  `json:"run_block_power_rating"`
  RunBlockRating           uint8  `json:"run_block_rating"`
  RunningStyleRating       string `json:"running_style_rating"`
  ShortRouteRunningRating  uint8  `json:"short_route_running_rating"`
  SpectacularCatchRating   uint8  `json:"spectacular_catch_rating"`
  SpeedRating              uint8  `json:"speed_rating"`
  SpinMoveRating           uint8  `json:"spin_move_rating"`
  StaminaRating            uint8  `json:"stamina_rating"`
  StiffArmRating           uint8  `json:"stiff_arm_rating"`
  StrengthRating           uint8  `json:"strength_rating"`
  TackleRating             uint8  `json:"tackle_rating"`
  Team 										 string `json:"team"`
  ThrowAccuracyDeepRating  uint8  `json:"throw_accuracy_deep_rating"`
  ThrowAccuracyMidRating 	 uint8  `json:"throw_accuracy_mid_rating"`
  ThrowAccuracyShortRating uint8  `json:"throw_accuracy_short_rating"`
  ThrowOnTheRunRating 		 uint8  `json:"throw_on_the_run_rating"`
  ThrowPowerRating 				 uint8  `json:"throw_power_rating"`
  ThrowUnderPressureRating uint8  `json:"throw_under_pressure_rating"`
  ToughnessRating 				 uint8  `json:"toughness_rating"`
  TruckingRating 					 uint8  `json:"trucking_rating"`
  Weight 									 uint8  `json:"weight"`
  NumYears             	   uint8  `json:"num_years"`
  ZoneCoverageRating 			 uint8  `json:"zone_coverage_rating"`
}
